/**
 * Test fixtures - reusable test data
 */

export const mockShop = {
  id: "test-shop-id",
  domain: "test-shop.myshopify.com",
  name: "Test Shop",
  email: "test@shop.com",
  accessToken: "test-access-token",
  scope: "read_products,write_products",
  status: "active",
  installedAt: new Date("2024-01-01"),
  uninstalledAt: null,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
};

export const mockProducts = [
  {
    id: 1,
    title: "Test Product 1",
    body_html: "<p>Test product description</p>",
    vendor: "Test Vendor",
    product_type: "Test Type",
    created_at: "2024-01-01T00:00:00Z",
    handle: "test-product-1",
    updated_at: "2024-01-01T00:00:00Z",
    published_at: "2024-01-01T00:00:00Z",
    template_suffix: null,
    status: "active",
    published_scope: "web",
    tags: "test, product",
    admin_graphql_api_id: "gid://shopify/Product/1",
    variants: [
      {
        id: 1,
        product_id: 1,
        title: "Default",
        price: "19.99",
        sku: "TEST-001",
        position: 1,
        inventory_policy: "deny",
        compare_at_price: "29.99",
        fulfillment_service: "manual",
        inventory_management: "shopify",
        option1: "Default",
        option2: null,
        option3: null,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
        taxable: true,
        barcode: "123456789",
        grams: 100,
        image_id: null,
        weight: 0.1,
        weight_unit: "kg",
        inventory_item_id: 1,
        inventory_quantity: 100,
        old_inventory_quantity: 100,
        requires_shipping: true,
        admin_graphql_api_id: "gid://shopify/ProductVariant/1",
      },
    ],
    options: [
      {
        id: 1,
        product_id: 1,
        name: "Title",
        position: 1,
        values: ["Default"],
      },
    ],
    images: [
      {
        id: 1,
        product_id: 1,
        position: 1,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
        alt: "Test Product Image",
        width: 1000,
        height: 1000,
        src: "https://cdn.shopify.com/test-image.jpg",
        variant_ids: [],
        admin_graphql_api_id: "gid://shopify/ProductImage/1",
      },
    ],
  },
];

export const mockOrders = [
  {
    id: 1,
    email: "customer@example.com",
    closed_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    number: 1001,
    note: null,
    token: "test-token",
    gateway: "shopify_payments",
    test: false,
    total_price: "19.99",
    subtotal_price: "19.99",
    total_weight: 100,
    total_tax: "0.00",
    taxes_included: true,
    currency: "USD",
    financial_status: "paid",
    confirmed: true,
    total_discounts: "0.00",
    total_line_items_price: "19.99",
    cart_token: "test-cart-token",
    buyer_accepts_marketing: false,
    name: "#1001",
    referring_site: "",
    landing_site: "",
    cancelled_at: null,
    cancel_reason: null,
    total_price_usd: "19.99",
    checkout_token: "test-checkout-token",
    reference: "test-reference",
    user_id: null,
    location_id: null,
    source_identifier: "test-source",
    source_url: null,
    processed_at: "2024-01-01T00:00:00Z",
    device_id: null,
    phone: "+1234567890",
    customer_locale: "en",
    app_id: 1,
    browser_ip: "127.0.0.1",
    landing_site_ref: null,
    order_number: 1001,
    discount_applications: [],
    discount_codes: [],
    note_attributes: [],
    payment_gateway_names: ["shopify_payments"],
    processing_method: "direct",
    checkout_id: 1,
    source_name: "web",
    fulfillment_status: null,
    tax_lines: [],
    tags: "",
    contact_email: "customer@example.com",
    order_status_url: "https://test-shop.myshopify.com/orders/1",
    presentment_currency: "USD",
    line_items: [
      {
        id: 1,
        variant_id: 1,
        title: "Test Product 1",
        quantity: 1,
        sku: "TEST-001",
        variant_title: "Default",
        vendor: "Test Vendor",
        fulfillment_service: "manual",
        product_id: 1,
        requires_shipping: true,
        taxable: true,
        gift_card: false,
        name: "Test Product 1 - Default",
        variant_inventory_management: "shopify",
        properties: [],
        product_exists: true,
        fulfillable_quantity: 1,
        grams: 100,
        price: "19.99",
        total_discount: "0.00",
        fulfillment_status: null,
        price_set: {},
        total_discount_set: {},
        discount_allocations: [],
        duties: [],
        admin_graphql_api_id: "gid://shopify/LineItem/1",
        tax_lines: [],
      },
    ],
  },
];

export const mockConfig = {
  id: "test-config-id",
  shopId: "test-shop-id",
  name: "Test Config",
  slug: "test-config",
  settings: {
    theme: {
      primaryColor: "#000000",
      secondaryColor: "#ffffff",
      fontFamily: "Inter",
      borderRadius: "8px",
      spacing: "16px",
    },
    blocks: [
      {
        id: "block-1",
        type: "hero",
        settings: {
          title: "Welcome",
          subtitle: "Test subtitle",
        },
        order: 0,
        enabled: true,
      },
    ],
  },
  status: "published",
  publishedAt: new Date("2024-01-01"),
  version: 1,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
};

export const mockWebhookPayload = {
  shop_domain: "test-shop.myshopify.com",
  topic: "orders/create",
  api_version: "2024-01",
  created_at: "2024-01-01T00:00:00Z",
  payload: mockOrders[0],
};
