name: Secrets Security Check

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, develop]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for scanning
      
      - name: TruffleHog OSS - Scan for leaked secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
          
      - name: Gitleaks - Detect hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check for .env files
        run: |
          # Check if any .env files are being committed
          env_files=$(git ls-files | grep -E '\.env' || true)
          if [ ! -z "$env_files" ]; then
            echo "❌ Found .env files in repository:"
            echo "$env_files"
            echo ""
            echo "Please remove these files and add them to .gitignore"
            exit 1
          fi
          echo "✅ No .env files found in repository"
          
      - name: Validate environment variable patterns
        run: |
          # Check for hardcoded localhost URLs in production code
          echo "Checking for hardcoded localhost references..."
          localhost_refs=$(grep -r "localhost:[0-9]" --include="*.ts" --include="*.tsx" --include="*.js" --exclude-dir=node_modules --exclude-dir=.next --exclude-dir=tests || true)
          
          if [ ! -z "$localhost_refs" ]; then
            echo "⚠️ Warning: Found hardcoded localhost references:"
            echo "$localhost_refs"
            echo "Consider using environment variables instead"
          fi
          
          # Check for potential API keys or secrets
          echo "Checking for potential exposed secrets..."
          suspicious=$(grep -r -E "(api[_-]?key|secret|token|password|pwd|passwd|credentials)" --include="*.ts" --include="*.tsx" --include="*.js" --exclude-dir=node_modules --exclude-dir=.next -i | grep -E "=\s*['\"][^'\"]{20,}['\"]" || true)
          
          if [ ! -z "$suspicious" ]; then
            echo "⚠️ Warning: Found potential hardcoded secrets:"
            echo "$suspicious"
            echo "Please review and move to environment variables"
          fi